[profile.default]
src = "src"
out = "out"
libs = ["lib"]


# Required for zkSync
zksolc = true
zksolc_version = '1.5.12' # or your preferred compatible version
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
